import type { Course, PricingPlan, Testimonial, User, AdminStats, Payment, Category } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Metaphysik', slug: 'metaphysik', description: 'Erforsche die Grundlagen der Wirklichkeit', coursesCount: 2, icon: '∞' },
  { id: '2', name: 'Heilung', slug: 'heilung', description: 'Energetische und holistische Heilmethoden', coursesCount: 1, icon: '✦' },
  { id: '3', name: 'Astrologie', slug: 'astrologie', description: 'Kosmische Einflüsse verstehen', coursesCount: 1, icon: '☽' },
  { id: '4', name: 'Hermetik', slug: 'hermetik', description: 'Alte Weisheitslehren und Alchemie', coursesCount: 1, icon: '⚗' },
  { id: '5', name: 'Traumarbeit', slug: 'traumarbeit', description: 'Das Unterbewusstsein erforschen', coursesCount: 1, icon: '◈' },
  { id: '6', name: 'Schamanismus', slug: 'schamanismus', description: 'Alte Heiltraditionen und Geisterwelt', coursesCount: 1, icon: '⬡' },
];

export const courses: Course[] = [
  {
    id: '1',
    slug: 'metaphysik-bewusstsein',
    title: 'Metaphysik & Bewusstsein',
    description: 'Eine tiefe Reise in die Natur des Bewusstseins und die metaphysischen Grundlagen der Existenz.',
    longDescription: `Tauche ein in die tiefsten Fragen der menschlichen Existenz. Dieser umfassende Kurs führt dich durch die Grundlagen der Metaphysik, von den antiken griechischen Denkern bis zu modernen Bewusstseinstheorien. Du wirst lernen, wie Gedanken die Wirklichkeit formen, welche Rolle das Bewusstsein im Universum spielt und wie du dein eigenes Bewusstseinsfeld erweitern kannst. Mit praktischen Meditationen, philosophischen Reflexionen und experimentellen Übungen transformierst du deine Weltanschauung grundlegend.`,
    instructor: 'Dr. Elena Mystika',
    instructorBio: 'Dr. Elena Mystika hat über 20 Jahre Erfahrung in Metaphysik und Bewusstseinsforschung. Sie hat an mehreren europäischen Universitäten gelehrt und zahlreiche Bücher veröffentlicht.',
    duration: 1440,
    lessonsCount: 48,
    price: 297,
    originalPrice: 497,
    rating: 4.9,
    reviewsCount: 342,
    image: '/courses/metaphysik.jpg',
    category: 'Metaphysik',
    level: 'Anfänger',
    tags: ['Bewusstsein', 'Philosophie', 'Meditation', 'Quantenphysik'],
    studentsCount: 1247,
    language: 'Deutsch',
    certificate: true,
    featured: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-06-01',
    modules: [
      {
        id: 'm1',
        title: 'Grundlagen der Metaphysik',
        description: 'Einführung in die grundlegenden Konzepte',
        order: 1,
        lessons: [
          { id: 'l1', title: 'Was ist Metaphysik?', description: 'Einführung und Überblick', duration: 25, isFree: true, order: 1 },
          { id: 'l2', title: 'Die Natur der Wirklichkeit', description: 'Verschiedene Wirklichkeitsmodelle', duration: 38, isFree: true, order: 2 },
          { id: 'l3', title: 'Bewusstsein als Grundprinzip', description: 'Panpsychismus und Bewusstseinstheorien', duration: 42, isFree: false, order: 3 },
          { id: 'l4', title: 'Zeit, Raum und Kausalität', description: 'Metaphysische Dimensionen', duration: 35, isFree: false, order: 4 },
        ],
      },
      {
        id: 'm2',
        title: 'Bewusstseinserweiterung',
        description: 'Praktische Techniken zur Bewusstseinserweiterung',
        order: 2,
        lessons: [
          { id: 'l5', title: 'Meditative Zustände', description: 'Alpha, Theta und Delta Gehirnwellen', duration: 45, isFree: false, order: 1 },
          { id: 'l6', title: 'Außerkörperliche Erfahrungen', description: 'Theorie und Praxis', duration: 52, isFree: false, order: 2 },
          { id: 'l7', title: 'Quantenbewusstsein', description: 'Moderne Theorien des Geistes', duration: 48, isFree: false, order: 3 },
        ],
      },
      {
        id: 'm3',
        title: 'Praktische Anwendung',
        description: 'Metaphysik im Alltag anwenden',
        order: 3,
        lessons: [
          { id: 'l8', title: 'Manifestation und Intention', description: 'Die Kraft des Denkens nutzen', duration: 40, isFree: false, order: 1 },
          { id: 'l9', title: 'Synchronizität erkennen', description: 'Meaningful coincidences', duration: 35, isFree: false, order: 2 },
          { id: 'l10', title: 'Integration ins tägliche Leben', description: 'Abschluss und Zusammenfassung', duration: 30, isFree: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: '2',
    slug: 'quantenheilung',
    title: 'Quantenheilung',
    description: 'Entdecke die heilenden Kräfte der Quantenphysik und energetischen Heilmethoden.',
    longDescription: `Quantenheilung verbindet modernste Erkenntnisse der Quantenphysik mit jahrtausendealten Heiltraditionen. In diesem Kurs lernst du, wie Energie auf subatomarer Ebene die Gesundheit beeinflusst, welche Rollen Gedanken und Emotionen bei der Heilung spielen und wie du Techniken wie PEMF, Bioresonanz und Energiearbeit in deine Heilpraxis integrieren kannst. Mit über 40 Stunden Videomaterial und praktischen Übungen wirst du ein tiefes Verständnis der energetischen Medizin entwickeln.`,
    instructor: 'Prof. Karl Richter',
    instructorBio: 'Prof. Karl Richter ist Physiker und Heiler mit 15 Jahren Erfahrung in der Brücke zwischen Wissenschaft und Spiritualität.',
    duration: 2400,
    lessonsCount: 56,
    price: 397,
    originalPrice: 597,
    rating: 4.8,
    reviewsCount: 218,
    image: '/courses/quantenheilung.jpg',
    category: 'Heilung',
    level: 'Fortgeschritten',
    tags: ['Quantenphysik', 'Energiearbeit', 'Gesundheit', 'Bioenergie'],
    studentsCount: 892,
    language: 'Deutsch',
    certificate: true,
    featured: true,
    createdAt: '2024-02-01',
    updatedAt: '2024-06-15',
    modules: [
      {
        id: 'm1',
        title: 'Grundlagen der Quantenphysik',
        description: 'Das Fundament verstehen',
        order: 1,
        lessons: [
          { id: 'l1', title: 'Quantenmechanik für Heiler', description: 'Einführung ohne Mathematik', duration: 35, isFree: true, order: 1 },
          { id: 'l2', title: 'Das Nullpunkt-Feld', description: 'Energie aus dem Vakuum', duration: 42, isFree: true, order: 2 },
          { id: 'l3', title: 'Verschränkung und Fernheilung', description: 'Nichtlokalität nutzen', duration: 48, isFree: false, order: 3 },
        ],
      },
      {
        id: 'm2',
        title: 'Energetische Heilmethoden',
        description: 'Praktische Heilmodalitäten',
        order: 2,
        lessons: [
          { id: 'l4', title: 'Bioenergetische Diagnose', description: 'Den Energiekörper lesen', duration: 55, isFree: false, order: 1 },
          { id: 'l5', title: 'Chakra-Heilung', description: 'Energiezentren ausbalancieren', duration: 60, isFree: false, order: 2 },
          { id: 'l6', title: 'Fernheilung praktizieren', description: 'Heilung über Distanz', duration: 45, isFree: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: '3',
    slug: 'astrologie-meisterkurs',
    title: 'Astrologie Meisterkurs',
    description: 'Meistere die Kunst der Astrologie von den Grundlagen bis zur professionellen Horoskop-Deutung.',
    longDescription: `Dieser umfassende Meisterkurs führt dich von den absoluten Grundlagen der Astrologie bis hin zur professionellen Horoskop-Deutung. Du lernst die zwölf Tierkreiszeichen, Planeten, Häuser und Aspekte kennen und verstehst, wie sie zusammenwirken. Mit über 100 Übungshoroskopen wirst du die Fähigkeit entwickeln, tiefgründige und präzise Deutungen zu erstellen. Der Kurs endet mit einem Abschluss-Zertifikat, das dich als zertifizierten Astrologen ausweist.`,
    instructor: 'Marina Sternenkind',
    instructorBio: 'Marina Sternenkind ist professionelle Astrologin mit 25 Jahren Erfahrung und Autorin von drei Bestseller-Büchern über Astrologie.',
    duration: 3600,
    lessonsCount: 72,
    price: 497,
    originalPrice: 797,
    rating: 4.95,
    reviewsCount: 521,
    image: '/courses/astrologie.jpg',
    category: 'Astrologie',
    level: 'Anfänger',
    tags: ['Horoskop', 'Planeten', 'Tierkreis', 'Mondphasen'],
    studentsCount: 2341,
    language: 'Deutsch',
    certificate: true,
    featured: true,
    createdAt: '2023-11-01',
    updatedAt: '2024-05-20',
    modules: [
      {
        id: 'm1',
        title: 'Die Grundlagen der Astrologie',
        description: 'Basis für alles Weitere',
        order: 1,
        lessons: [
          { id: 'l1', title: 'Geschichte der Astrologie', description: 'Von Babylon bis heute', duration: 30, isFree: true, order: 1 },
          { id: 'l2', title: 'Die zwölf Tierkreiszeichen', description: 'Eigenschaften und Symbolik', duration: 45, isFree: true, order: 2 },
          { id: 'l3', title: 'Die Planeten und ihre Bedeutung', description: 'Sonne, Mond und Planeten', duration: 50, isFree: false, order: 3 },
          { id: 'l4', title: 'Die zwölf Häuser', description: 'Lebensbereiche im Horoskop', duration: 55, isFree: false, order: 4 },
        ],
      },
      {
        id: 'm2',
        title: 'Horoskop erstellen und deuten',
        description: 'Von der Theorie zur Praxis',
        order: 2,
        lessons: [
          { id: 'l5', title: 'Das Geburtshoroskop', description: 'Natal Chart erstellen', duration: 60, isFree: false, order: 1 },
          { id: 'l6', title: 'Aspekte verstehen', description: 'Planetare Beziehungen', duration: 48, isFree: false, order: 2 },
          { id: 'l7', title: 'Erste Deutungen', description: 'Übungshoroskope', duration: 75, isFree: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: '4',
    slug: 'hermetik-alchemie',
    title: 'Hermetik & Alchemie',
    description: 'Entschlüssle die Geheimnisse der hermetischen Philosophie und der spirituellen Alchemie.',
    longDescription: `Die hermetische Philosophie ist eine der mächtigsten spirituellen Traditionen der westlichen Welt. In diesem Kurs wirst du die sieben hermetischen Prinzipien verstehen, die Symbolsprache der Alchemie entschlüsseln und lernen, wie du diese alten Weisheiten zur persönlichen Transformation nutzen kannst. Von der Tabula Smaragdina bis zum Kybalion – dieser Kurs gibt dir einen umfassenden Einblick in diese faszinierende Tradition.`,
    instructor: 'Magnus Hermes',
    instructorBio: 'Magnus Hermes ist Philosoph, Mystiker und Autor mit einem Doktortitel in Religionswissenschaften und 18 Jahren Erfahrung in hermetischer Philosophie.',
    duration: 1800,
    lessonsCount: 42,
    price: 347,
    originalPrice: 547,
    rating: 4.85,
    reviewsCount: 189,
    image: '/courses/hermetik.jpg',
    category: 'Hermetik',
    level: 'Fortgeschritten',
    tags: ['Kybalion', 'Alchemie', 'Philosophie', 'Esoterik'],
    studentsCount: 678,
    language: 'Deutsch',
    certificate: true,
    featured: false,
    createdAt: '2024-03-01',
    updatedAt: '2024-06-10',
    modules: [
      {
        id: 'm1',
        title: 'Hermetische Grundprinzipien',
        description: 'Die sieben Prinzipien verstehen',
        order: 1,
        lessons: [
          { id: 'l1', title: 'Das Prinzip des Geistes', description: 'Alles ist Geist', duration: 40, isFree: true, order: 1 },
          { id: 'l2', title: 'Polarität und Rhythmus', description: 'Dualität überwinden', duration: 38, isFree: true, order: 2 },
          { id: 'l3', title: 'Ursache und Wirkung', description: 'Kein Zufall im Universum', duration: 42, isFree: false, order: 3 },
        ],
      },
      {
        id: 'm2',
        title: 'Spirituelle Alchemie',
        description: 'Innere Transmutation',
        order: 2,
        lessons: [
          { id: 'l4', title: 'Die alchemistische Symbolsprache', description: 'Symbole entschlüsseln', duration: 55, isFree: false, order: 1 },
          { id: 'l5', title: 'Das Grosse Werk', description: 'Opus Magnus verstehen', duration: 60, isFree: false, order: 2 },
          { id: 'l6', title: 'Praktische Transmutation', description: 'Innere Wandlung vollziehen', duration: 45, isFree: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: '5',
    slug: 'traumarbeit-unterbewusstsein',
    title: 'Traumarbeit & Unterbewusstsein',
    description: 'Entschlüssle die Botschaften deiner Träume und nutze die Kraft deines Unterbewusstseins.',
    longDescription: `Träume sind Fenster zur Seele. In diesem praktischen Kurs lernst du, deine Träume zu erinnern, aufzuzeichnen und zu deuten. Du wirst die Symbolsprache des Unterbewusstseins verstehen, luzides Träumen erlernen und lernen, wie du Träume zur persönlichen Heilung und Kreativitätsförderung nutzen kannst. Mit geführten Meditationen und praktischen Traumtageübungen wirst du eine tiefe Verbindung zu deiner inneren Weisheit aufbauen.`,
    instructor: 'Dr. Sophia Luna',
    instructorBio: 'Dr. Sophia Luna ist Psychologin, Traumforscherin und zertifizierte Traumtherapeutin mit über 12 Jahren klinischer Erfahrung.',
    duration: 1200,
    lessonsCount: 36,
    price: 247,
    originalPrice: 397,
    rating: 4.75,
    reviewsCount: 267,
    image: '/courses/traumarbeit.jpg',
    category: 'Traumarbeit',
    level: 'Anfänger',
    tags: ['Träume', 'Unterbewusstsein', 'Luzides Träumen', 'Psychologie'],
    studentsCount: 1089,
    language: 'Deutsch',
    certificate: false,
    featured: false,
    createdAt: '2024-01-20',
    updatedAt: '2024-05-30',
    modules: [
      {
        id: 'm1',
        title: 'Grundlagen der Traumarbeit',
        description: 'Verstehen und Erinnern',
        order: 1,
        lessons: [
          { id: 'l1', title: 'Warum wir träumen', description: 'Wissenschaft und Spiritualität der Träume', duration: 28, isFree: true, order: 1 },
          { id: 'l2', title: 'Das Traumtagebuch', description: 'Träume festhalten', duration: 22, isFree: true, order: 2 },
          { id: 'l3', title: 'Traumsymbole deuten', description: 'Archetypische Bilder', duration: 35, isFree: false, order: 3 },
        ],
      },
      {
        id: 'm2',
        title: 'Luzides Träumen',
        description: 'Bewusst im Traum',
        order: 2,
        lessons: [
          { id: 'l4', title: 'Was ist Luzides Träumen?', description: 'Einführung und Theorie', duration: 30, isFree: false, order: 1 },
          { id: 'l5', title: 'MILD und WILD Techniken', description: 'Bewusstsein im Traum entwickeln', duration: 40, isFree: false, order: 2 },
          { id: 'l6', title: 'Im Traum handeln', description: 'Luzide Träume nutzen', duration: 45, isFree: false, order: 3 },
        ],
      },
    ],
  },
  {
    id: '6',
    slug: 'schamanische-praxis',
    title: 'Schamanische Praxis',
    description: 'Entdecke die uralten schamanischen Traditionen und lerne, mit Geisterwelten zu kommunizieren.',
    longDescription: `Schamanismus ist eine der ältesten spirituellen Traditionen der Menschheit. Dieser Kurs führt dich in die Grundlagen des Schamanismus ein: die Kosmologie der drei Welten, Seelenreise und Schamanisches Trommeln, Krafttiere und Hilfsgeister, Heilzeremonien und Reinigungsrituale. Basierend auf Traditionen aus Sibirien, Nordamerika und den Anden lernst du eine lebendige, praktische Spiritualität kennen, die du in deinen modernen Alltag integrieren kannst.`,
    instructor: 'Wolf Donnerpfad',
    instructorBio: 'Wolf Donnerpfad wurde von schamanischen Lehrern aus Sibirien und Peru ausgebildet und praktiziert seit 20 Jahren schamanische Heilarbeit.',
    duration: 2100,
    lessonsCount: 54,
    price: 447,
    originalPrice: 647,
    rating: 4.9,
    reviewsCount: 156,
    image: '/courses/schamanismus.jpg',
    category: 'Schamanismus',
    level: 'Anfänger',
    tags: ['Schamanismus', 'Seelenreise', 'Krafttier', 'Ritual'],
    studentsCount: 534,
    language: 'Deutsch',
    certificate: true,
    featured: false,
    createdAt: '2024-04-01',
    updatedAt: '2024-06-20',
    modules: [
      {
        id: 'm1',
        title: 'Schamanische Kosmologie',
        description: 'Die drei Welten',
        order: 1,
        lessons: [
          { id: 'l1', title: 'Was ist Schamanismus?', description: 'Geschichte und Verbreitung', duration: 35, isFree: true, order: 1 },
          { id: 'l2', title: 'Obere, mittlere und untere Welt', description: 'Kosmische Karte', duration: 40, isFree: true, order: 2 },
          { id: 'l3', title: 'Der Weltbaum', description: 'Axis Mundi und Verbindung', duration: 32, isFree: false, order: 3 },
        ],
      },
      {
        id: 'm2',
        title: 'Praktiken und Rituale',
        description: 'Schamanische Techniken',
        order: 2,
        lessons: [
          { id: 'l4', title: 'Schamanisches Trommeln', description: 'Den Herzschlag der Erde fühlen', duration: 50, isFree: false, order: 1 },
          { id: 'l5', title: 'Die Seelenreise', description: 'Bewusstsein reist', duration: 60, isFree: false, order: 2 },
          { id: 'l6', title: 'Krafttier finden', description: 'Spirituelle Verbündete', duration: 45, isFree: false, order: 3 },
        ],
      },
    ],
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: '1',
    type: 'basis',
    name: 'Basis',
    price: 29,
    description: 'Perfekt für Einsteiger, die erste Schritte in die mystische Welt wagen.',
    features: [
      '3 Kurse nach Wahl',
      'Zugang zu Community',
      'Monatliche Live-Sessions',
      'Lernfortschritt tracken',
      'Mobile App',
      'E-Mail-Support',
    ],
    highlighted: false,
    ctaLabel: 'Jetzt starten',
    maxCourses: 3,
  },
  {
    id: '2',
    type: 'premium',
    name: 'Premium',
    price: 49,
    originalPrice: 79,
    description: 'Unbegrenzter Zugang für ernsthaft Suchende auf dem spirituellen Pfad.',
    features: [
      'Alle Kurse unbegrenzt',
      'KI-Lernassistent',
      'Wöchentliche Live-Sessions',
      'Zertifizierungsprüfungen',
      'Community + Mentoring',
      'Prioritäts-Support',
      'Offline-Downloads',
      'Exklusive Meditationen',
    ],
    highlighted: true,
    ctaLabel: 'Empfohlen wählen',
    maxCourses: 'unlimited',
  },
  {
    id: '3',
    type: 'masterclass',
    name: 'Masterclass',
    price: 99,
    description: 'Das ultimative Erlebnis für Meister und spirituelle Lehrer.',
    features: [
      'Alles in Premium',
      '1:1 Coaching-Sessions',
      'Früher Zugang zu neuen Kursen',
      'Lehrer-Zertifizierung',
      'Eigene Kurse erstellen',
      'Revenue-Share Programm',
      'VIP-Community',
      'Persönlicher Lernplan',
      'API-Zugang',
    ],
    highlighted: false,
    ctaLabel: 'Masterclass wählen',
    maxCourses: 'unlimited',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sabrina Kessler',
    role: 'Heilpraktikerin',
    content: 'Die Arkanum Akademie hat mein Leben verändert. Besonders der Quantenheilung-Kurs hat mir ein völlig neues Verständnis von Gesundheit und Energie gegeben. Absolut empfehlenswert!',
    rating: 5,
    courseTitle: 'Quantenheilung',
  },
  {
    id: '2',
    name: 'Thomas Bergmann',
    role: 'Ingenieur & spiritueller Suchender',
    content: 'Als Naturwissenschaftler war ich zunächst skeptisch. Aber der Metaphysik-Kurs hat mich überzeugt – fundiert, tiefgründig und dennoch praxisnah. Großartige Qualität!',
    rating: 5,
    courseTitle: 'Metaphysik & Bewusstsein',
  },
  {
    id: '3',
    name: 'Lena Mondlicht',
    role: 'Yogalehrerin',
    content: 'Der Astrologie-Meisterkurs ist phänomenal. Marina Sternenkind erklärt komplexe Konzepte so klar und zugänglich. Nach 3 Monaten kann ich bereits vollständige Horoskope deuten!',
    rating: 5,
    courseTitle: 'Astrologie Meisterkurs',
  },
  {
    id: '4',
    name: 'Andreas Walther',
    role: 'Therapeut',
    content: 'Die Traumarbeit hat mir geholfen, tiefe unbewusste Muster zu erkennen und zu transformieren. Dr. Sophias Ansatz ist wissenschaftlich fundiert und gleichzeitig spirituell tiefgründig.',
    rating: 5,
    courseTitle: 'Traumarbeit & Unterbewusstsein',
  },
  {
    id: '5',
    name: 'Petra Himmelblau',
    role: 'Lehrerin',
    content: 'Ich war begeistert von der Qualität der Inhalte und der unterstützenden Community. Die KI-Assistentin hilft mir wirklich, die Konzepte tiefer zu verstehen.',
    rating: 4,
    courseTitle: 'Hermetik & Alchemie',
  },
  {
    id: '6',
    name: 'Michael Sonnenwend',
    role: 'Unternehmer',
    content: 'Der Schamanismus-Kurs hat mir eine völlig neue Dimension der Spiritualität eröffnet. Wolf Donnerpfad ist ein außergewöhnlicher Lehrer. Die Seelenreisen sind transformativ!',
    rating: 5,
    courseTitle: 'Schamanische Praxis',
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sophia Sternbild',
    email: 'sophia@example.com',
    role: 'admin',
    joinedAt: '2023-01-15',
    lastLoginAt: '2024-06-25',
    enrolledCourses: ['1', '2', '3'],
    completedLessons: ['l1', 'l2', 'l3', 'l4', 'l5'],
    subscription: {
      id: 's1',
      userId: '1',
      plan: 'masterclass',
      status: 'active',
      startDate: '2024-01-01',
      endDate: '2025-01-01',
      price: 99,
      autoRenew: true,
    },
  },
  {
    id: '2',
    name: 'Max Mondlicht',
    email: 'max@example.com',
    role: 'member',
    joinedAt: '2024-02-10',
    lastLoginAt: '2024-06-24',
    enrolledCourses: ['1', '3'],
    completedLessons: ['l1', 'l2'],
    subscription: {
      id: 's2',
      userId: '2',
      plan: 'premium',
      status: 'active',
      startDate: '2024-02-10',
      endDate: '2025-02-10',
      price: 49,
      autoRenew: true,
    },
  },
  {
    id: '3',
    name: 'Anna Lichtpfad',
    email: 'anna@example.com',
    role: 'member',
    joinedAt: '2024-03-22',
    lastLoginAt: '2024-06-20',
    enrolledCourses: ['2'],
    completedLessons: [],
    subscription: {
      id: 's3',
      userId: '3',
      plan: 'basis',
      status: 'active',
      startDate: '2024-03-22',
      endDate: '2025-03-22',
      price: 29,
      autoRenew: false,
    },
  },
  {
    id: '4',
    name: 'Klaus Erdenwächter',
    email: 'klaus@example.com',
    role: 'instructor',
    joinedAt: '2023-06-01',
    lastLoginAt: '2024-06-23',
    enrolledCourses: ['4', '5', '6'],
    completedLessons: ['l1', 'l2', 'l3', 'l4', 'l5', 'l6'],
    subscription: {
      id: 's4',
      userId: '4',
      plan: 'masterclass',
      status: 'active',
      startDate: '2023-06-01',
      endDate: '2024-06-01',
      price: 99,
      autoRenew: true,
    },
  },
  {
    id: '5',
    name: 'Maria Feuerherz',
    email: 'maria@example.com',
    role: 'member',
    joinedAt: '2024-05-15',
    lastLoginAt: '2024-06-18',
    enrolledCourses: ['1'],
    completedLessons: ['l1'],
    subscription: {
      id: 's5',
      userId: '5',
      plan: 'basis',
      status: 'trial',
      startDate: '2024-05-15',
      endDate: '2024-06-15',
      price: 0,
      autoRenew: false,
    },
  },
];

export const adminStats: AdminStats = {
  totalRevenue: 48750,
  monthlyRevenue: 8320,
  totalUsers: 6781,
  activeSubscriptions: 2347,
  totalCourses: 6,
  completionRate: 68,
};

export const mockPayments: Payment[] = [
  { id: 'p1', userId: '1', userName: 'Sophia Sternbild', amount: 99, plan: 'masterclass', status: 'paid', date: '2024-06-01', method: 'Kreditkarte' },
  { id: 'p2', userId: '2', userName: 'Max Mondlicht', amount: 49, plan: 'premium', status: 'paid', date: '2024-05-28', method: 'PayPal' },
  { id: 'p3', userId: '3', userName: 'Anna Lichtpfad', amount: 29, plan: 'basis', status: 'paid', date: '2024-05-20', method: 'SEPA' },
  { id: 'p4', userId: '5', userName: 'Maria Feuerherz', amount: 49, plan: 'premium', status: 'pending', date: '2024-06-10', method: 'Kreditkarte' },
  { id: 'p5', userId: '4', userName: 'Klaus Erdenwächter', amount: 99, plan: 'masterclass', status: 'paid', date: '2024-06-15', method: 'Kreditkarte' },
];
